### ISSUE TITLE
Improve UI  of result and notification

### ISSUE THREAD

**Issue by Chensokheng** [ajmaln/easyku#21]
I would like to improve the UI of component Result and Notification.
@ajmaln  You can check the result below. If you agreed, I will make the PR. 

# before
<img width="1792" alt="Screen Shot 2020-10-06 at 1 02 19 PM" src="https://user-images.githubusercontent.com/52232579/95165022-5b87ff80-07d5-11eb-9870-b4f9ce80940b.png">

# After
<img width="1792" alt="Screen Shot 2020-10-06 at 1 10 16 PM" src="https://user-images.githubusercontent.com/52232579/95165044-66db2b00-07d5-11eb-95fe-cea195294f1e.png">

**Comment by ajmaln** [comment]
Looks cool please make PR
